# React App build,test & deployment through CircleCi CICD Pipeline to AWS S3 bucket.

version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Installing AWS CLI"
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: 
          name: "Build stage-Navigating to ./app folder & Installing npm & then doing ls"
          commands: |
            cd ./app
            npm install
            ls -al 
      - run:
          name: "Running npm build command to build React App then doing ls & then navigating to ./app/build to do ls"
          commands: |
            npm run build
            ls -al
            cd ./app/build
            ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: 
          name: "Test stage-Doing ls & then navigating to ./app folder to do ls"
          commands: |
            ls -al
            cd ./app
            ls -al
      - run:
          name: "Running npm run test command to test the build that happened in build stage & then doing ls and then navigating to build folder to do ls"
          commands: |
            npm run test
            ls -al
            cd build
            ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: 
          name: "Deploy stage-Navigating to ./app/build folder to do ls"
          commands: |
            cd ./app/build
            ls -al
      - run: 
          name: "Deploying the React App build files to AWS S3 bucket named react-app-cicd-deploy"
          commands:
            aws s3 sync ./app/build s3://react-app-cicd-deploy

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test