# CircleCi Pipeline with jobs - lint,test,build,deploy

version: 2.1

orbs:
  kelvin: kelvinkfli/demo@1.0.0

jobs:
  lint:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - kelvin/lint
  test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - kelvin/test
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Build docker Image"
          command: echo "Image Successfully Built"
      - run:
          name: "Publish Image"
          command: echo "Image successfully published"  # ECR/Docker registry/etc
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Deploy image using ____"
          command: echo "Image deployed Successfully"  # awscli commands/create and upgrade helm charts/etc

workflows:
  test_build_deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

