# CircleCi Pipeline with jobs - lint,test,build,deploy.

version: 2.1

orbs:
  kelvin: kelvinkfli/demo@1.0.0

jobs:
  lint:
    parameters:
      preinstall-foo:
        type: boolean
        default: false
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: 
          name: "Checking the when condition whether True or False"
          command: echo "preinstall-foo parameter condition value is << parameters.preinstall-foo >>"
      - when:
          condition:  << parameters.preinstall-foo >>
          steps:
            - run: 
                name: "When condition meet to True"
                command: echo "Preinstall started as preinstall-foo parameter condition value meet to True"
            - kelvin/lint
      - unless:
          condition: << parameters.preinstall-foo >>
          steps:
            - run: 
                name: "When condition meet to False"
                command: echo "Preinstall can't be started as preinstall-foo parameter condition value is false"
  test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - kelvin/test
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Build docker Image"
          command: echo "Image Successfully Built"
      - run:
          name: "Publish Image"
          command: echo "Image successfully published"  # ECR/Docker registry/etc
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Deploy image using ____"
          command: echo "Image deployed Successfully"  # awscli commands/create and upgrade helm charts/etc

workflows:
  test_build_deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

