# React App build,test & deployment through CircleCi CICD Pipeline to AWS S3 bucket.

version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Installing AWS CLI"
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && ls -al && npm run build && ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: ls -al && cd ./app && ls -al && npm run test && ls -al && cd build && ls -al
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./app/build && ls -al
      - run: aws s3 sync ./app/build s3://react-app-cicd-deploy

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test